theme: jekyll-theme-minimal

# Setup
title:        escapee.org | voterbot.github.io
tagline:      Some javascript sketches. B-spline / NURBS / other stuff
baseurl:      ""
paginate:     2
locale:       "en"

# About/contact
author:
  name:       Author name
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
